import {
  Resource,
  Project,
  Assignment,
  ProjectManager,
  TimeOff,
  Task,
} from "./types";

export const projectManagers: ProjectManager[] = [
  { id: "pm1", name: "Sarah Johnson", color: "bg-blue-500" },
  { id: "pm2", name: "Michael Chen", color: "bg-purple-500" },
];

export const resources: Resource[] = [
  // Employees
  {
    id: "e1",
    name: "John Smith",
    type: "employee",
    jobTitle: "Senior Carpenter",
    skills: ["carpentry", "framing", "finish work"],
    certifications: ["OSHA 30", "First Aid"],
    hourlyRate: 45,
    address: "123 Main St",
    city: "Lancaster",
    imageUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
  },
  {
    id: "e2",
    name: "Maria Rodriguez",
    type: "employee",
    jobTitle: "Electrician",
    skills: ["electrical", "wiring", "troubleshooting"],
    certifications: ["Master Electrician", "OSHA 10"],
    hourlyRate: 50,
    address: "456 Oak Ave",
    city: "Reading",
    imageUrl:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop",
  },
  {
    id: "e3",
    name: "David Thompson",
    type: "employee",
    jobTitle: "Plumber",
    skills: ["plumbing", "pipefitting", "hvac"],
    certifications: ["Journeyman Plumber", "OSHA 10"],
    hourlyRate: 48,
    address: "789 Pine Rd",
    city: "York",
    imageUrl:
      "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop",
  },
  {
    id: "e4",
    name: "Emily Chen",
    type: "employee",
    jobTitle: "Painter",
    skills: ["painting", "drywall", "finishing"],
    certifications: ["OSHA 10", "Lead Safe"],
    hourlyRate: 38,
    address: "321 Elm St",
    city: "Harrisburg",
    imageUrl:
      "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=200&h=200&fit=crop",
  },
  {
    id: "e5",
    name: "Robert Wilson",
    type: "employee",
    jobTitle: "Foreman",
    skills: ["project management", "carpentry", "supervision"],
    certifications: ["OSHA 30", "CPR", "Forklift"],
    hourlyRate: 55,
    address: "654 Maple Dr",
    city: "Lancaster",
    imageUrl:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop",
  },
  // Contractors
  {
    id: "c1",
    name: "ABC Drywall Inc.",
    type: "contractor",
    skills: ["drywall", "taping", "texturing"],
    certifications: ["Licensed", "Insured"],
    hourlyRate: 150,
    city: "Philadelphia",
    contractorHeadcount: 6,
  },
  {
    id: "c2",
    name: "Premium Flooring Co.",
    type: "contractor",
    skills: ["hardwood", "tile", "carpet"],
    certifications: ["Licensed", "Bonded"],
    hourlyRate: 175,
    city: "Allentown",
    contractorHeadcount: 4,
  },
  {
    id: "c3",
    name: "Elite HVAC Services",
    type: "contractor",
    skills: ["hvac", "ventilation", "refrigeration"],
    certifications: ["EPA Certified", "Licensed"],
    hourlyRate: 200,
    city: "Reading",
    contractorHeadcount: 8,
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    name: "Riverside Office Complex",
    address: "500 River Road",
    city: "Lancaster",
    state: "PA",
    managerId: "pm1",
    supervisorId: "e5",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-08-31"),
    color: "bg-blue-500",
    tasks: [
      { id: "t1", projectId: "p1", title: "Demolition", completed: false },
      { id: "t2", projectId: "p1", title: "Framing", completed: false },
      {
        id: "t3",
        projectId: "p1",
        title: "Electrical rough-in",
        completed: false,
      },
      {
        id: "t4",
        projectId: "p1",
        title: "Plumbing rough-in",
        completed: false,
      },
      {
        id: "t5",
        projectId: "p1",
        title: "Drywall installation",
        completed: false,
      },
      {
        id: "t6",
        projectId: "p1",
        title: "Painting and finishing",
        completed: false,
      },
    ],
  },
  {
    id: "p2",
    name: "Heritage Mall Renovation",
    address: "1200 Commerce Blvd",
    city: "Reading",
    state: "PA",
    managerId: "pm2",
    supervisorId: "e5",
    startDate: new Date("2025-06-15"),
    endDate: new Date("2025-09-15"),
    color: "bg-purple-500",
    tasks: [
      { id: "t7", projectId: "p2", title: "Store closures", completed: false },
      {
        id: "t8",
        projectId: "p2",
        title: "Interior demolition",
        completed: false,
      },
      { id: "t9", projectId: "p2", title: "New storefronts", completed: false },
      {
        id: "t10",
        projectId: "p2",
        title: "Common area upgrades",
        completed: false,
      },
      {
        id: "t11",
        projectId: "p2",
        title: "Flooring replacement",
        completed: false,
      },
    ],
  },
  {
    id: "p3",
    name: "Tech Center Build-Out",
    address: "800 Innovation Way",
    city: "Harrisburg",
    state: "PA",
    managerId: "pm1",
    supervisorId: "e5",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-10-15"),
    color: "bg-green-500",
    tasks: [
      {
        id: "t12",
        projectId: "p3",
        title: "Server room construction",
        completed: false,
      },
      {
        id: "t13",
        projectId: "p3",
        title: "Electrical systems",
        completed: false,
      },
      {
        id: "t14",
        projectId: "p3",
        title: "HVAC installation",
        completed: false,
      },
      {
        id: "t15",
        projectId: "p3",
        title: "Security systems",
        completed: false,
      },
    ],
  },
  {
    id: "p4",
    name: "Medical Clinic Expansion",
    address: "300 Health Plaza",
    city: "York",
    state: "PA",
    managerId: "pm2",
    supervisorId: "e5",
    startDate: new Date("2025-06-20"),
    endDate: new Date("2025-09-30"),
    color: "bg-orange-500",
    tasks: [
      {
        id: "t16",
        projectId: "p4",
        title: "Foundation work",
        completed: false,
      },
      {
        id: "t17",
        projectId: "p4",
        title: "Medical gas lines",
        completed: false,
      },
      {
        id: "t18",
        projectId: "p4",
        title: "Clean room construction",
        completed: false,
      },
      {
        id: "t19",
        projectId: "p4",
        title: "Equipment installation",
        completed: false,
      },
    ],
  },
];

export const assignments: Assignment[] = [
  // MAY ASSIGNMENTS

  // John Smith (Senior Carpenter) - May assignments
  {
    id: "a_may1",
    resourceId: "e1",
    projectId: "p1",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-02"),
    hoursPerDay: 8,
    tasks: ["Site preparation"],
    driveTime: 15,
  },
  {
    id: "a_may2",
    resourceId: "e1",
    projectId: "p2",
    startDate: new Date("2025-05-05"),
    endDate: new Date("2025-05-09"),
    hoursPerDay: 8,
    tasks: ["Initial assessment"],
    driveTime: 45,
  },
  {
    id: "a_may3",
    resourceId: "e1",
    projectId: "p1",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-16"),
    hoursPerDay: 8,
    tasks: ["Foundation work"],
    driveTime: 15,
  },
  {
    id: "a_may4",
    resourceId: "e1",
    projectId: "p3",
    startDate: new Date("2025-05-19"),
    endDate: new Date("2025-05-23"),
    hoursPerDay: 8,
    tasks: ["Pre-construction planning"],
    driveTime: 50,
  },
  {
    id: "a_may5",
    resourceId: "e1",
    projectId: "p1",
    startDate: new Date("2025-05-27"),
    endDate: new Date("2025-05-30"),
    hoursPerDay: 8,
    tasks: ["Structural preparation"],
    driveTime: 15,
  },

  // Maria Rodriguez (Electrician) - May assignments
  {
    id: "a_may6",
    resourceId: "e2",
    projectId: "p2",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-02"),
    hoursPerDay: 8,
    tasks: ["Electrical assessment"],
    driveTime: 30,
  },
  {
    id: "a_may7",
    resourceId: "e2",
    projectId: "p1",
    startDate: new Date("2025-05-06"),
    endDate: new Date("2025-05-09"),
    hoursPerDay: 8,
    tasks: ["Conduit installation"],
    driveTime: 30,
  },
  {
    id: "a_may8",
    resourceId: "e2",
    projectId: "p4",
    startDate: new Date("2025-05-13"),
    endDate: new Date("2025-05-16"),
    hoursPerDay: 8,
    tasks: ["Planning medical electrical"],
    driveTime: 25,
  },
  {
    id: "a_may9",
    resourceId: "e2",
    projectId: "p3",
    startDate: new Date("2025-05-20"),
    endDate: new Date("2025-05-23"),
    hoursPerDay: 8,
    tasks: ["Data center planning"],
    driveTime: 50,
  },
  {
    id: "a_may10",
    resourceId: "e2",
    projectId: "p1",
    startDate: new Date("2025-05-27"),
    endDate: new Date("2025-05-30"),
    hoursPerDay: 8,
    tasks: ["Main panel prep"],
    driveTime: 30,
  },

  // David Thompson (Plumber) - May assignments
  {
    id: "a_may11",
    resourceId: "e3",
    projectId: "p1",
    startDate: new Date("2025-05-05"),
    endDate: new Date("2025-05-07"),
    hoursPerDay: 8,
    tasks: ["Underground plumbing"],
    driveTime: 25,
  },
  {
    id: "a_may12",
    resourceId: "e3",
    projectId: "p4",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-16"),
    hoursPerDay: 8,
    tasks: ["Medical gas planning"],
    driveTime: 25,
  },
  {
    id: "a_may13",
    resourceId: "e3",
    projectId: "p2",
    startDate: new Date("2025-05-19"),
    endDate: new Date("2025-05-21"),
    hoursPerDay: 8,
    tasks: ["Mall plumbing assessment"],
    driveTime: 20,
  },
  {
    id: "a_may14",
    resourceId: "e3",
    projectId: "p3",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-30"),
    hoursPerDay: 8,
    tasks: ["Cooling system planning"],
    driveTime: 50,
  },

  // Emily Chen (Painter) - May assignments (prep work)
  {
    id: "a_may15",
    resourceId: "e4",
    projectId: "p1",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-14"),
    hoursPerDay: 8,
    tasks: ["Surface preparation"],
    driveTime: 50,
  },
  {
    id: "a_may16",
    resourceId: "e4",
    projectId: "p2",
    startDate: new Date("2025-05-19"),
    endDate: new Date("2025-05-23"),
    hoursPerDay: 8,
    tasks: ["Color consultation"],
    driveTime: 45,
  },
  {
    id: "a_may17",
    resourceId: "e4",
    projectId: "p4",
    startDate: new Date("2025-05-27"),
    endDate: new Date("2025-05-30"),
    hoursPerDay: 8,
    tasks: ["Medical facility color planning"],
    driveTime: 25,
  },

  // Robert Wilson (Foreman) - May supervision
  {
    id: "a_may18",
    resourceId: "e5",
    projectId: "p1",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-09"),
    hoursPerDay: 4,
    tasks: ["Project kickoff supervision"],
    driveTime: 15,
  },
  {
    id: "a_may19",
    resourceId: "e5",
    projectId: "p2",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-16"),
    hoursPerDay: 4,
    tasks: ["Mall project planning"],
    driveTime: 30,
  },
  {
    id: "a_may20",
    resourceId: "e5",
    projectId: "p4",
    startDate: new Date("2025-05-19"),
    endDate: new Date("2025-05-23"),
    hoursPerDay: 4,
    tasks: ["Medical facility planning"],
    driveTime: 25,
  },
  {
    id: "a_may21",
    resourceId: "e5",
    projectId: "p3",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-30"),
    hoursPerDay: 4,
    tasks: ["Tech center pre-planning"],
    driveTime: 50,
  },

  // Contractor assignments for May
  {
    id: "a_may22",
    resourceId: "c1",
    projectId: "p1",
    startDate: new Date("2025-05-19"),
    endDate: new Date("2025-05-23"),
    hoursPerDay: 8,
    tasks: ["Drywall material delivery"],
    driveTime: 60,
  },
  {
    id: "a_may23",
    resourceId: "c2",
    projectId: "p2",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-30"),
    hoursPerDay: 8,
    tasks: ["Flooring samples and planning"],
    driveTime: 45,
  },
  {
    id: "a_may24",
    resourceId: "c3",
    projectId: "p3",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-16"),
    hoursPerDay: 8,
    tasks: ["HVAC system design"],
    driveTime: 50,
  },

  // JUNE ASSIGNMENTS

  // John Smith (Senior Carpenter) - Working on multiple projects
  {
    id: "a1",
    resourceId: "e1",
    projectId: "p1",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-13"),
    hoursPerDay: 8,
    tasks: ["Demolition", "Framing preparation"],
    driveTime: 15,
  },
  {
    id: "a2",
    resourceId: "e1",
    projectId: "p2",
    startDate: new Date("2025-06-16"),
    endDate: new Date("2025-06-27"),
    hoursPerDay: 8,
    tasks: ["Interior demolition", "Framing new storefronts"],
    driveTime: 45,
  },
  {
    id: "a3",
    resourceId: "e1",
    projectId: "p3",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-11"),
    hoursPerDay: 8,
    tasks: ["Server room framing"],
    driveTime: 50,
  },
  {
    id: "a4",
    resourceId: "e1",
    projectId: "p1",
    startDate: new Date("2025-07-14"),
    endDate: new Date("2025-07-25"),
    hoursPerDay: 8,
    tasks: ["Office build-out"],
    driveTime: 15,
  },

  // Maria Rodriguez (Electrician) - Multiple projects
  {
    id: "a5",
    resourceId: "e2",
    projectId: "p1",
    startDate: new Date("2025-06-09"),
    endDate: new Date("2025-06-20"),
    hoursPerDay: 8,
    tasks: ["Electrical rough-in", "Panel installation"],
    driveTime: 30,
  },
  {
    id: "a6",
    resourceId: "e2",
    projectId: "p3",
    startDate: new Date("2025-07-08"),
    endDate: new Date("2025-07-19"),
    hoursPerDay: 8,
    tasks: ["Server room electrical", "UPS installation"],
    driveTime: 50,
  },
  {
    id: "a7",
    resourceId: "e2",
    projectId: "p4",
    startDate: new Date("2025-07-22"),
    endDate: new Date("2025-08-02"),
    hoursPerDay: 8,
    tasks: ["Medical equipment wiring"],
    driveTime: 25,
  },

  // David Thompson (Plumber) - Multiple projects
  {
    id: "a8",
    resourceId: "e3",
    projectId: "p1",
    startDate: new Date("2025-06-09"),
    endDate: new Date("2025-06-13"),
    hoursPerDay: 8,
    tasks: ["Plumbing rough-in"],
    driveTime: 25,
  },
  {
    id: "a9",
    resourceId: "e3",
    projectId: "p2",
    startDate: new Date("2025-06-23"),
    endDate: new Date("2025-06-27"),
    hoursPerDay: 8,
    tasks: ["Bathroom renovations"],
    driveTime: 20,
  },
  {
    id: "a10",
    resourceId: "e3",
    projectId: "p4",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-12"),
    hoursPerDay: 8,
    tasks: ["Medical gas installation"],
    driveTime: 25,
  },
  {
    id: "a11",
    resourceId: "e3",
    projectId: "p3",
    startDate: new Date("2025-07-15"),
    endDate: new Date("2025-07-19"),
    hoursPerDay: 8,
    tasks: ["Server room plumbing"],
    driveTime: 50,
  },

  // Emily Chen (Painter) - Multiple projects
  {
    id: "a12",
    resourceId: "e4",
    projectId: "p1",
    startDate: new Date("2025-06-30"),
    endDate: new Date("2025-07-11"),
    hoursPerDay: 8,
    tasks: ["Prime and paint offices"],
    driveTime: 50,
  },
  {
    id: "a13",
    resourceId: "e4",
    projectId: "p2",
    startDate: new Date("2025-07-14"),
    endDate: new Date("2025-07-25"),
    hoursPerDay: 8,
    tasks: ["Paint common areas"],
    driveTime: 45,
  },
  {
    id: "a14",
    resourceId: "e4",
    projectId: "p4",
    startDate: new Date("2025-08-05"),
    endDate: new Date("2025-08-16"),
    hoursPerDay: 8,
    tasks: ["Medical facility painting"],
    driveTime: 25,
  },

  // Robert Wilson (Foreman) - Supervising all projects
  {
    id: "a15",
    resourceId: "e5",
    projectId: "p1",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-13"),
    hoursPerDay: 4,
    tasks: ["Supervise demolition and framing"],
    driveTime: 15,
  },
  {
    id: "a16",
    resourceId: "e5",
    projectId: "p2",
    startDate: new Date("2025-06-16"),
    endDate: new Date("2025-06-20"),
    hoursPerDay: 4,
    tasks: ["Oversee mall renovation start"],
    driveTime: 30,
  },
  {
    id: "a17",
    resourceId: "e5",
    projectId: "p4",
    startDate: new Date("2025-06-23"),
    endDate: new Date("2025-06-27"),
    hoursPerDay: 4,
    tasks: ["Medical facility supervision"],
    driveTime: 25,
  },
  {
    id: "a18",
    resourceId: "e5",
    projectId: "p3",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-05"),
    hoursPerDay: 4,
    tasks: ["Tech center kickoff"],
    driveTime: 50,
  },

  // ABC Drywall Inc. - Multiple projects
  {
    id: "a19",
    resourceId: "c1",
    projectId: "p1",
    startDate: new Date("2025-06-23"),
    endDate: new Date("2025-07-04"),
    hoursPerDay: 8,
    tasks: ["Drywall installation", "Taping and mudding"],
    driveTime: 60,
  },
  {
    id: "a20",
    resourceId: "c1",
    projectId: "p2",
    startDate: new Date("2025-07-07"),
    endDate: new Date("2025-07-18"),
    hoursPerDay: 8,
    tasks: ["Mall drywall work"],
    driveTime: 45,
  },
  {
    id: "a21",
    resourceId: "c1",
    projectId: "p3",
    startDate: new Date("2025-07-28"),
    endDate: new Date("2025-08-08"),
    hoursPerDay: 8,
    tasks: ["Server room drywall"],
    driveTime: 65,
  },

  // Premium Flooring Co. - Multiple projects
  {
    id: "a22",
    resourceId: "c2",
    projectId: "p2",
    startDate: new Date("2025-07-28"),
    endDate: new Date("2025-08-08"),
    hoursPerDay: 8,
    tasks: ["Remove old flooring", "Install new flooring"],
    driveTime: 45,
  },
  {
    id: "a23",
    resourceId: "c2",
    projectId: "p1",
    startDate: new Date("2025-08-11"),
    endDate: new Date("2025-08-22"),
    hoursPerDay: 8,
    tasks: ["Office flooring installation"],
    driveTime: 60,
  },
  {
    id: "a24",
    resourceId: "c2",
    projectId: "p4",
    startDate: new Date("2025-08-26"),
    endDate: new Date("2025-09-06"),
    hoursPerDay: 8,
    tasks: ["Medical grade flooring"],
    driveTime: 25,
  },

  // Elite HVAC Services - Multiple projects
  {
    id: "a25",
    resourceId: "c3",
    projectId: "p1",
    startDate: new Date("2025-06-16"),
    endDate: new Date("2025-06-20"),
    hoursPerDay: 8,
    tasks: ["HVAC system installation"],
    driveTime: 30,
  },
  {
    id: "a26",
    resourceId: "c3",
    projectId: "p3",
    startDate: new Date("2025-07-22"),
    endDate: new Date("2025-08-02"),
    hoursPerDay: 8,
    tasks: ["Server room cooling system"],
    driveTime: 50,
  },
  {
    id: "a27",
    resourceId: "c3",
    projectId: "p4",
    startDate: new Date("2025-08-12"),
    endDate: new Date("2025-08-23"),
    hoursPerDay: 8,
    tasks: ["Medical HVAC systems"],
    driveTime: 25,
  },
  {
    id: "a28",
    resourceId: "c3",
    projectId: "p2",
    startDate: new Date("2025-08-26"),
    endDate: new Date("2025-09-06"),
    hoursPerDay: 8,
    tasks: ["Mall HVAC upgrade"],
    driveTime: 30,
  },
  // Additional June assignments for fuller schedule

  // More assignments for early June
  {
    id: "a_june1",
    resourceId: "e1",
    projectId: "p4",
    startDate: new Date("2025-06-03"),
    endDate: new Date("2025-06-05"),
    hoursPerDay: 4,
    tasks: ["Medical facility carpentry"],
    driveTime: 25,
  },
  {
    id: "a_june2",
    resourceId: "e2",
    projectId: "p2",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-06"),
    hoursPerDay: 8,
    tasks: ["Mall electrical prep"],
    driveTime: 30,
  },
  {
    id: "a_june3",
    resourceId: "e3",
    projectId: "p3",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-04"),
    hoursPerDay: 8,
    tasks: ["Server room plumbing prep"],
    driveTime: 50,
  },
  {
    id: "a_june4",
    resourceId: "e4",
    projectId: "p1",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-06"),
    hoursPerDay: 8,
    tasks: ["Primer application"],
    driveTime: 50,
  },
  {
    id: "a_june5",
    resourceId: "e4",
    projectId: "p3",
    startDate: new Date("2025-06-09"),
    endDate: new Date("2025-06-13"),
    hoursPerDay: 8,
    tasks: ["Tech center paint prep"],
    driveTime: 50,
  },
  {
    id: "a_june6",
    resourceId: "c1",
    projectId: "p4",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-06"),
    hoursPerDay: 8,
    tasks: ["Medical facility drywall prep"],
    driveTime: 25,
  },
  {
    id: "a_june7",
    resourceId: "c1",
    projectId: "p2",
    startDate: new Date("2025-06-09"),
    endDate: new Date("2025-06-13"),
    hoursPerDay: 8,
    tasks: ["Mall partition walls"],
    driveTime: 45,
  },
  {
    id: "a_june8",
    resourceId: "c2",
    projectId: "p1",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-06"),
    hoursPerDay: 8,
    tasks: ["Office subfloor prep"],
    driveTime: 60,
  },
  {
    id: "a_june9",
    resourceId: "c2",
    projectId: "p3",
    startDate: new Date("2025-06-09"),
    endDate: new Date("2025-06-13"),
    hoursPerDay: 8,
    tasks: ["Anti-static flooring prep"],
    driveTime: 65,
  },
  {
    id: "a_june10",
    resourceId: "c3",
    projectId: "p2",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-06"),
    hoursPerDay: 8,
    tasks: ["Mall HVAC assessment"],
    driveTime: 30,
  },
  {
    id: "a_june11",
    resourceId: "c3",
    projectId: "p4",
    startDate: new Date("2025-06-09"),
    endDate: new Date("2025-06-13"),
    hoursPerDay: 8,
    tasks: ["Medical HVAC planning"],
    driveTime: 25,
  },
];

export const timeOffs: TimeOff[] = [
  // Add some time offs for realism
  {
    id: "to1",
    resourceId: "e1",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-26"),
    reason: "Memorial Day",
  },
  {
    id: "to2",
    resourceId: "e2",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-26"),
    reason: "Memorial Day",
  },
  {
    id: "to3",
    resourceId: "e3",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-26"),
    reason: "Memorial Day",
  },
  {
    id: "to4",
    resourceId: "e4",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-26"),
    reason: "Memorial Day",
  },
  {
    id: "to5",
    resourceId: "e5",
    startDate: new Date("2025-05-26"),
    endDate: new Date("2025-05-26"),
    reason: "Memorial Day",
  },
  {
    id: "to6",
    resourceId: "e3",
    startDate: new Date("2025-06-16"),
    endDate: new Date("2025-06-20"),
    reason: "Vacation",
  },
  {
    id: "to7",
    resourceId: "e4",
    startDate: new Date("2025-06-16"),
    endDate: new Date("2025-06-18"),
    reason: "Personal leave",
  },
];

// Helper functions
export const getResourceById = (id: string) =>
  resources.find((r) => r.id === id);
export const getProjectById = (id: string) => projects.find((p) => p.id === id);
export const getProjectManagerById = (id: string) =>
  projectManagers.find((pm) => pm.id === id);
export const getAssignmentsByResourceId = (resourceId: string) =>
  assignments.filter((a) => a.resourceId === resourceId);
export const getAssignmentsByProjectId = (projectId: string) =>
  assignments.filter((a) => a.projectId === projectId);
